version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app_usr:app_pwd_1234@converter-db.crrcdkkacufx.us-east-1.rds.amazonaws.com:5432/converter
      FLASK_ENV: production
      UPLOAD_FOLDER: /usr/src/app/files
      APP_MODE: production
      AWS_ACCESS_KEY_ID: ASIAZLPHUOXOIJ2KCPHZ
      AWS_SECRET_ACCESS_KEY: im82qCqZ5Pj42bPdigctstxDHkYdArVZXuQQ9/JX
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEFcaDHPwNs0keUdj/dF62yLMAe47JgL2iuvKQk+SLobDkR/CjXcgyuNplXywL6XfwLPtDjX0MBOdDZVSRXPMw/PCTkGEzs0FBwzKahCq1k2pSFg9U6O7WkyK88Fcd/ATf0nBy27DR7lel/+CCVNf+T3+7sVQkSGhBPcLdxx0RRq16Qh3UEahbT+Rz2AWQ63YXUnhMdxK8zMc0sf4Sb0t4KLCUfWY2qejIs7TDFZdqSPXqj0D2Pc8zQQlrjkbA+HW2E60ntN8aoiT0RtFv9BMBrsPrOKmoImGK1Z0YO7wsij53J+NBjItMIepZmfv+yWzSpuzawVBeTkiSkwS7T90vkyQ/ljAYXxtCxBeyMIcxhX+/dGT

    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8080"
    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]