version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: worker_sqs/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      DSN: postgresql://app_usr:app_pwd_1234@converter-db.crrcdkkacufx.us-east-1.rds.amazonaws.com:5432/converter
      NOTIFICATION_ENDPOINT: https://hooks.slack.com/services/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
      LIMIT_PROCESSING_TEST: 600
      AWS_ACCESS_KEY_ID: ASIAZLPHUOXOE7QTBMWU
      AWS_SECRET_ACCESS_KEY: EbuRruy+yMMS4TR9ZTuZJqv+ZvuUmC2bFH7IqL/f
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEEQaDLPOW7N/EJ6DgFCSsiLMAWtqbdkvGmTOUCCqQWgbx0YwJp0voYup/2j0DGfJuOG4eHmFZRApOkfuER/f7+pyrIm4AtuoIh9abjIHngwkRZ8WWIHvnb8spA7JrMYHe700Zjzpb2Px4oljlSC4GCicFYdzAIXTbbrp1Nvuv2ZYCBEvisC4JwGX0nxQJ5SxNMq00idtEMVLyF/Gz4pK7jETKWQCzCA7gMNwF9Y6j3x4GZ0ZOivPbYys/lnCGaK2xNQr5X8g9sCzpZ5DlF8l2UClqJPILKMZGtyYrmaayii7uZuNBjIt6bWmG5ZK3esqwi2CTgM+Fue6G7i4OCfvUzCU1EDoQzx2KNBuxnrVzy5krs6+
    volumes:
      - type: bind
        source: ./logs
        target: /queue/logs
      - type: bind
        source: ./files
        target: /queue/files