version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app_usr:app_pwd@db:5432/app_db
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/usr/src/app/files
      - APP_MODE=production
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]

  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app_usr
      - POSTGRES_PASSWORD=app_pwd
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"

  worker:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DSN: postgresql://app_usr:app_pwd@db:5432/app_db
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./files
        target: /queue/files
      - type: bind
        source: ./logs
        target: /queue/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: