version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app_usr:app_pwd_1234@converter-db.crrcdkkacufx.us-east-1.rds.amazonaws.com:5432/converter
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/home/ubuntu/Proyecto-Grupo4-202120/files
      - APP_MODE=production
      - CELERY_BROKER_URL=172.31.88.145:6379
      - CELERY_RESULT_BACKEND=172.31.88.145:6379

    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]

  worker:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DSN: postgresql://app_usr:app_pwd@db:5432/app_db
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./files
        target: /queue/files
      - type: bind
        source: ./logs
        target: /queue/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: