version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app_usr:app_pwd@127.0.0.1:5432/converter
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/usr/src/app/files
      - APP_MODE=production
    ports:
      - "80:5000"
    volumes:
      - .:/usr/src/app/
    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]

  worker:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
      DSN: postgresql://app_usr:app_pwd@db:5432/app_db
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./files
        target: /queue/files
      - type: bind
        source: ./logs
        target: /queue/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: