version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: worker_sqs/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      DSN: postgresql://app_usr:app_pwd_1234@converter-db.crrcdkkacufx.us-east-1.rds.amazonaws.com:5432/converter
      NOTIFICATION_ENDPOINT: https://hooks.slack.com/services/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
      LIMIT_PROCESSING_TEST: 600
      AWS_ACCESS_KEY_ID: ASIAZLPHUOXOKYFYIAIE
      AWS_SECRET_ACCESS_KEY: fJRojehSc1bcoIknHA4XE1BPMMALY6I8Y68fX5HY
      AWS_SESSION_TOKEN: FwoGZXIvYXdzEFwaDFrY7zVtVFlRS8T6tSLMARRN1D9gAltInBC6cn4rFjD0yIafrJ+SAu2sryugD21oH5D4EbwsY7LPQw1oP5k8BbVstOxqLmwDXj5KK3U1yf0czv1VxJS/z226U+OvBPDF9HIGgB6WfhvlvFyDdLR9vnNCrNzWeEWaL7JwXNQP4YfiUCCecJ2tJr1UZZzRlWhQD7lIq82+5Xi76uuvcNqlyQKNRYJ1vFAEHMMB+lJCbleR8TUBV89jBsTtSRMuHbU48aXjtTFSg1MgHwhLnhPyuoDHu5uB3ld4ed9xdyjD7KCNBjItRVIGrpzv7ETnLkVIyYk04COHmSEKNJvwGaYs5DClbkf9rPoPW42vdhFcTPLx
    volumes:
      - type: bind
        source: ./logs
        target: /queue/logs
      - type: bind
        source: ./files
        target: /queue/files