version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: celery/Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      DSN: postgresql://app_usr:app_pwd@db:5432/app_db
    depends_on:
      - redis
    volumes:
      - type: bind
        source: ./files
        target: /queue/files
      - type: bind
        source: ./logs
        target: /queue/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: