version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app_usr:app_pwd_1234@converter-db.crrcdkkacufx.us-east-1.rds.amazonaws.com:5432/converter
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/usr/src/app/files
      - APP_MODE=production
      - CELERY_BROKER_URL=redis://172.31.88.145:6379/0
      - CELERY_RESULT_BACKEND=redis://172.31.88.145:6379/0
      - AWS_ACCESS_KEY_ID=ASIAZLPHUOXOKRMPYSNZ
      - AWS_SECRET_ACCESS_KEY=qXek8UMAX7My9K9sGvj0nOs4A7vzjmVKH7vnd8mi
      - AWS_SESSION_TOKEN=FwoGZXIvYXdzEGoaDO6ARo0CG8EnkBXMOiLMAYjqz6KWmZ+sRONvQ9GQZTud5LQb72SUBNsJGf6T/2SnMKtkq73QtVOtX9g2v7Wg2pfwGVirVdLtcO4SvGTljG4Ut8Z5toyOYfLLxcIIHHIAieuijQLjgbex9pSK5/D1eR7yZqn20Hi2/B7VBtJiM+KAQEmCsBJHo5x8l9CnnMe/yU7i9EpyXA0NyR7GB8XrrVs/2LnwTWnsVePGDGEZybsyxwYk9LAdb9byPIBNf2Ib0uq8+QvXI2PCWYP9fFQvomO6ybkE2CeUy/l2VijLzuuMBjIttpa4mnfkWZNaBt35Nw5oFzlujFoVxoD8FeceZOYCbhFffH207kalZo/u76OD

    ports:
      - "8080:8080"

    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]