version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app_usr:app_pwd@127.0.0.1:5432/converter
      - FLASK_ENV=production
    ports:
      - "80:5000"
    volumes:
      - .:/usr/src/app/
    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]

  worker:
    build:
      context: ./celery
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: [ './celery:/queue' ]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  postgres_data: