version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://app_usr:app_pwd@db:5432/app_db
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app/
    restart: always
    entrypoint: ["./config/prod/entrypoint.sh"]
  db:
    image: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app_usr
      - POSTGRES_PASSWORD=app_pwd
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
volumes:
  postgres_data: