"""empty message

Revision ID: 231cabc74632
Revises: f3d760bbd06e
Create Date: 2021-10-21 04:13:26.035061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231cabc74632'
down_revision = 'f3d760bbd06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('original_file_path', sa.String(length=256), nullable=True))
    op.add_column('tasks', sa.Column('new_file_path', sa.String(length=128), nullable=True))
    op.drop_column('tasks', 'file_name')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('tasks', sa.Column('file_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'new_file_path')
    op.drop_column('tasks', 'original_file_path')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
