"""empty message

Revision ID: f3d760bbd06e
Revises: caf910ba143b
Create Date: 2021-10-21 03:49:40.950977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d760bbd06e'
down_revision = 'caf910ba143b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=64), nullable=False),
    sa.Column('new_format', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('timestamp', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
